# Page settings

baseURL = "https://viniciusou.github.io/"
languageCode = "en"
title = "Vinicius Uemura's resume"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "viniciusou"
    description = "Vinicius Uemura's resume"







    [params.profile]
        enable = true
        name = "Vinicius Uemura"
        tagline = "Software Developer"
        avatar = "me.png"







    [params.contact]
        enable = true
        location = "Maringá - Brazil"

        [[params.contact.list]]
        style = "fas"
        icon = "fa-phone-square"
        url = "tel:#"
        text = "+55 44 98419-8873"
        [[params.contact.list]]
        style = "fab"
        icon = "fa-github-square"
        url = "//github.com/viniciusou"
        text = "viniciusou"
        [[params.contact.list]]
        style = "fab"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/vuemura"
        text = "vuemura"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "ASP.NET"
        [[params.skills.list.items]]
        details = ".NET Core"
        [[params.skills.list.items]]
        details = "Angular"
        [[params.skills.list.items]]
        details = "Entity Framework"
        [[params.skills.list.items]]
        details = "Xamarin"
        [[params.skills.list.items]]
        details = "C#/Go"
        [[params.skills.list.items]]
        details = "Hugo"
        [[params.skills.list.items]]
        details = "Sql Server"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Git/Bitbucket"
        [[params.skills.list.items]]
        details = "TDD"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Scrum"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    








    [params.certifications]
        enable = true

        [[params.certifications.list]]
        name = "C# Microsoft Specialist"
        body = "483 - Programming in C#"
        date = "2015"
        

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MBA in Mobile Development"
        university = "IGTI"
        dates = "2016 - 2017"
        [[params.education.list]]
        degree = "BASc in Chemical Engineering"
        university = "Universidade Estadual de Maringá"
        dates = "2002 - 2007"





    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Portuguese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Fluent"
        [[params.languages.list]]
        name = "Spanish"
        level = "Fluent"








    [params.summary]
        enable = true
        text = "Software developer with 8+ years experience crafting web and mobile apps. Knowledge of front-end and back-end languages, frameworks and best coding practices. Experience working in agile teams.  Fluent in English and Spanish."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Developer"
        dates = "2018 - 2019"
        company = "Blend IT"
        details = "Participated in the Electrolux Home+ app development (Android/iOS). The app is used to control smart appliances. Developed using Xamarin, ASP.NET MVC and IoT communication interface."

        [[params.experience.list]]
        title = "Software Developer"
        dates = "2017 - 2018"
        company = "Madero"
        details = "Developed mobile apps in Xamarin using MvvmCross and Prism frameworks. Developed back-end systems using ASP.NET C#."
        
        [[params.experience.list]]
        title = "Web Developer"
        dates = "2017"
        company = "Mirum Agency"
        details = "Developed web applications using Angular and ASP.NET MVC. Developed websites in Drupal."

        [[params.experience.list]]
        title = "Sofware Developer"
        dates = "2015 - 2017"
        company = "Pix"
        details = "Led development of PixPay (Android/iOS) and Trinnus (Android/iOS) mobile apps. Migrated company servers and database services achieving 60% cost savings. Developed .NET C# back-end systems for POS and mobile apps."

        [[params.experience.list]]
        title = ".NET Developer"
        dates = "2015"
        company = "Indra"
        details = "Developed web apps using ASP.NET, Ajax, Javascript and CSS. Developed C# and VB applications for insurance industry. Designed stored procedures, queries and views in SQL Server."

        [[params.experience.list]]
        title = "Engineer / Software Developer"
        dates = "2010 - 2013"
        company = "Soteica"
        details = "Developed engineering software applications with .NET Framework (C# and VB). Designed database stored procedures, queries and views in SQL Server. Collaborated in the development of 3D Industrial Simulator (using Microsoft XNA)."








    [params.information]
        enable = true

        [[params.information.list]]
        title = "Volunteering"
        [[params.information.list.items]]
        details = "2019 · Travelled as a volunteer worker through South America"
        [[params.information.list.items]]
        details = "2018 · Taught digital literacy and Scratch programming language for children"

        [[params.information.list]]
        title = "Interests"
        [[params.information.list.items]]
        details = "Travelling, Sports, Gardening"









